[project]
name = "StreamChecker"
version = "0.1.0"
description = "Scrapes TMDB to find streaming options for movies and TV shows."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2",
]

[project.scripts]
streamCheck = "StreamChecker.scrape:main"